# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='m_name',
        ),
    ]
