# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_user_detail_m_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='f_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='l_name',
        ),
    ]
