# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20160822_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='password',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='personal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
