# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20160822_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
