# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auth_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_model',
        ),
    ]
