# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_auto_20160904_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='org_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=200)),
                ('orgadd', models.TextField()),
                ('org_email', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('defaultpassword', models.CharField(max_length=200)),
            ],
        ),
    ]
