# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_org_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org_detail',
            old_name='org_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='org_detail',
            old_name='org_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='org_detail',
            old_name='defaultpassword',
            new_name='password',
        ),
    ]
